### ISSUE TITLE
Please update NuGet package: Current one doesn't work under IIS

### ISSUE THREAD

**Issue by hyrmedia** [psquickitjayant/log4net-loggly#14]
The NuGet package does not work for me under IIS, although it DOES seem to work when running under IIS Express. Yet when I build from source, it seems to work fine in both cases.

At a glance, it appears there's only been one commit since the Nuget package was built:
https://github.com/psquickitjayant/log4net-loggly/commit/12cc0995ce599a38709b0429789206d76e8389bb

Can you please update the NuGet package with the latest version?

**Comment by psquickitjayant** [comment]
Nuget package is built everytime we make an update. See here https://www.nuget.org/packages/log4net-loggly/
