### ISSUE TITLE
Provide nuget package with .net45 support and use async System.Net.HttpClient in it

### ISSUE THREAD

**Issue by maximpashuk** [psquickitjayant/log4net-loggly#15]
Since .NET 4.5 HttpClient class is supported with async method SendAsync.
I think logging via http should always be async, and HttpClient is the best way to do it.
Any plans of use it in loggly?

I know log4net itself not provide .net45 version, but I can use log4net lib in compatibility mode and loggly lib in .net45 since .net45 is complete replacement of .net40

PS. Aslo I can see very small bug in lib, if I not specify Tag property in appender, it add "/tags" in url to anyway. My opinion that is should not.

**Comment by psquickitjayant** [comment]
@maximpashuk  We are supporting 4.0 as most of the users are still working on 4.0. You can fork this repo to create your own version to support 4.5. 

Regarding tags, we always set a default tag in the events, if no value is provided in the config.

**Comment by maximpashuk** [comment]
Okay I understand .net 45 HttpClient cannot be used.

But anyway we can use async versions of methods
https://github.com/psquickitjayant/log4net-loggly/blob/master/source/log4net-loggly/LogglyClient.cs#L30

BeginGetRequestString\EndGetRequestString pair instead of sync GetRequestString.

For example, PostLog use this approach.
https://github.com/statianzo/PostLog/blob/master/src/PostLog/HttpAppender.cs#L65

**Comment by psquickitjayant** [comment]
Is it possible for you to update the code and send the pull request? Then we can review and test, and merge the code
