### ISSUE TITLE
Consider to use just one thread to asynchronously push events

### ISSUE THREAD

**Issue by micdenny** [psquickitjayant/log4net-loggly#16]
In other words, avoid to use [`ThreadPool.QueueUserWorkItem`](https://github.com/psquickitjayant/log4net-loggly/blob/master/source/log4net-loggly/LogglyAppender.cs#L51) per event, because this could cause thread starvation on high-load application,  which means if the application tries to log a burst of events, and the thread used to manage the send of the event waits on IO resource to complete (as it does), could cause slowness on all the application if it relies on ThreadPool as well.

This is because ThreadPool tries to avoid creating more thread than the predefined MinThreads (that by default are one per core in console app, more on asp.net app), actually it slows down the creation by a factor of 2 threads per second (this could also been changed in new framework, for sure was like that in 3.5, but whenever algorithm it is used now, its purpose is to avoid creating too much threads), the slowness could happen only on the first burst, and then if the application is really stable enqueuing the same amount of tasks, the application could perform well (this is all about the thread pool algorithm), but more often I saw application doing that with thread pool simply going mad (of course it depends on many many factors).

The following instead is a good log4net async implementation that uses a dispatcher-way, always consuming one thread, but just one to push all the events that are coming: https://github.com/logentries/le_dotnet/blob/master/src/LogentriesCore/AsyncLogger.cs

**Comment by mostlyjason** [comment]
This seems like a good idea. I added it to our backlog to implement. If you get to it before us we'd be happy to send you some swag as a thanks.

**Comment by jonbe242** [comment]
Any plans for this yet?

LE also has this "AreAllQueuesEmpty" method that I would like to use when my apps are about to terminate (https://github.com/logentries/le_dotnet/blob/master/src/LogentriesCore/AsyncLogger.cs#L91). Can you add that too while implementing this?

**Comment by psquickitjayant** [comment]
thanks for the suggestion @jonbe242 . I am trying to get this implemented.

**Comment by jonbe242** [comment]
Maybe it is a good idea to override AppenderSkeleton.OnClose and to empty any queue(s) on this callback.

**Comment by Korijn** [comment]
Might I recommend simply providing synchronous appenders and advising users to take on log4net.async as a dependency?

https://github.com/cjbhaines/Log4Net.Async/

**Comment by psquickitjayant** [comment]
This issue has been addressed in https://github.com/psquickitjayant/log4net-loggly/commit/6e01fe0a8acfe6431fae7b211b7168348736e69a
