### ISSUE TITLE
Using Active Property Values results in empty string when using provider

### ISSUE THREAD

**Issue by brianyeckley-gr** [psquickitjayant/log4net-loggly#17]
Following this pattern when putting a pattern in the ThreadContext results in an empty string.  https://logging.apache.org/log4net/release/manual/contexts.html

Example of our provider:

    public class RequestIdProvider : IFixingRequired
    {
        public object GetFixedObject()
        {
            return ToString();
        }

        public override string ToString()
        {
            return RequestContext.RequestId ?? "";
        }
    }

And how we used it:

    log4net.ThreadContext.Properties["RequestId"] = new RequestIdProvider();

Using it without the provider works correctly:

    log4net.ThreadContext.Properties["RequestId"] = RequestContext.RequestId ?? "";

The problem seems to be that GetFixedObject is not called because the IFixingRequired attribute (http://logging.apache.org/log4net/log4net-1.2.12/release/sdk/log4net.Core.IFixingRequired.html) is not being honored, which is required for a buffered appender.

**Comment by psquickitjayant** [comment]
hi @brianyeckley-gr 

sorry, earlier I was busy in some other stuff, could not get a chance to look at it.

You need to call ToString(). You can try the following code.

```
log4net.ThreadContext.Properties["RequestId"] = new RequestIdProvider().ToString();
```
This works fine for me.

**Comment by brianyeckley-gr** [comment]
Thanks for the feedback.  In your example, that just puts the current value of the provider into a static string into the logs.  It will never change.  The purpose of the provider is to wrap something dynamic, such as HttpContext, so that at log write time the current value is stored into the logs.

My example puts it on the ThreadContext but a better one would be using the GlobalContext.  You put the provider in once and for each log write a new dynamic value gets written because the HttpContext would be different for each user.

In the link above (https://logging.apache.org/log4net/release/manual/contexts.html) scroll down to Active Property Values to see log4net's explanation of it.

Thanks

**Comment by psquickitjayant** [comment]
Ah! I got your point. Well this is a great idea to add! I will try to achieve this next weekend! :+1:

**Comment by psquickitjayant** [comment]
@brianyeckley-gr try the latest release , ifixing required is now implemented

add your context keys like shown below

```
<logicalThreadContextKeys value="lkey1,lkey2" />
<globalContextKeys value="gkey1,gkey2" />
```

https://github.com/psquickitjayant/log4net-loggly/tree/adding-contexts
https://github.com/psquickitjayant/log4net-loggly/releases/tag/v8.0.0
https://www.nuget.org/packages/log4net-loggly/8.0.0-beta

cc: @mostlyjason

**Comment by brianyeckley-gr** [comment]
Great news, thanks!  We'll work on integrating this very soon.
