### ISSUE TITLE
loggly rootUrl need be changed

### ISSUE THREAD

**Issue by cellmigrate** [psquickitjayant/log4net-loggly#23]
Following the config example given in README, I always got 403 invalid API key. After digging a bit deeper,  I found we need change the rootUrl to the value below:

`<rootUrl value="http://logs-01.loggly.com/inputs" />`

Not sure if this is a server side change recently ...

**Comment by psquickitjayant** [comment]
Can you make the changes and submit a pull request?

**Comment by cellmigrate** [comment]
sure, i can do it if you grant me permission for this repo. 
I think the proper fix might be not update the README, we can add the missing part below: 
`var url = String.Concat(config.RootUrl, "inputs/", config.InputKey);`

**Comment by psquickitjayant** [comment]
you need to fork it and update your repo. Then you can send the pull request to this repo.

**Comment by antonmos** [comment]
I think the correct solution might to get logMode to actually default to something (like the documentation says it should). Btw, I wonder whether 'bulk' is a good default.

**Comment by psquickitjayant** [comment]
Hey, the issue is fixed. https://github.com/psquickitjayant/log4net-loggly/commit/898f78ef9d8092129cefbf0998f2373c62a66c4c 

Download latest package from Nuget (7.2.1) https://www.nuget.org/packages/log4net-loggly/

@cellmigrate  @antonmos
